version: '3.8'

services:
  postgres:
    container_name: treina-hub-db
    image: postgres
    ports:
      - 5432:5432
    environment:
       POSTGRES_USER: admin
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB: treina-hub-db
       PGDATA: /data/postgres
    volumes:
    - ./data/pg:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d treina-hub-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  treinahub-service:
    container_name: treinahub-service
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "npm rebuild canvas --build-from-source && npx prisma generate && npm run start:dev"]
    volumes:
      - ./:/usr/src/app
    ports:
      - 3334:3334
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}