services:
  postgres:
    image: postgres:16
    container_name: treina_hub_db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "treina_hub_prod"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d treina_hub_prod"]
      interval: 10s
      timeout: 5s
      retries: 5
